project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Tirmo"
  navbar:
    left:
      - href: library_dashboard.qmd
        text: Library Dashboard
      - href: resource_settings.qmd
        text: Resource Settings

format:
  html:
    theme: cosmo
    toc: false