project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Tirmo"
  navbar:
    left:
      - href: library_dashboard.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true