project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Tirmo"
  navbar:
    left:
      - href: library_dashboard.qmd
        text: Library Dashboard

format:
  html:
    theme: yeti
    toc: false