---
title: "Tercen Library Dashboard"
format: 
  dashboard:
    theme: default
    orientation: rows
    expandable: true
    scrolling: true
editor: visual
echo: false
warning: false
message: false
---

```{r}
library(dplyr)
library(jsonlite)

url <- "https://raw.githubusercontent.com/tercen/app-library/refs/heads/master/tercen/library-report.json"
data <- jsonlite::fromJSON(url)

data$success_documents$status <- "success"
data$notest_documents$status <- "no_test"
data$blacklisted_documents$status <- "error"
data$failed_documents$status <- "error"
data$no_release_documents <- as_tibble(data$no_release_documents) |>
  rename(url = "value") |>
  mutate(status = "no_release")

df <- bind_rows(data) |>
  mutate(kind = case_when(
    grepl("_operator", url) ~ "Operator",
    grepl("_app", url) ~ "App",
    grepl("_template", url) ~ "Template",
    grepl("_dataset", url) ~ "Dataset",
    TRUE ~ "Unknown"
  ))

tb <- table(df$kind, df$status)
pt <- round(prop.table(tb, margin = 1) * 100, 2)


lib_url <- "https://raw.githubusercontent.com/tercen/app-library/refs/heads/master/tercen/library.json"
lib_data <- jsonlite::fromJSON(lib_url)[["repos"]] |> as_tibble() |>
  mutate(kind = case_when(
    grepl("_operator", url) ~ "Operator",
    grepl("_app", url) ~ "App",
    grepl("_template", url) ~ "Template",
    grepl("_dataset", url) ~ "Dataset",
    TRUE ~ "Unknown"
  ))
```


## Row {.flow}

```{r}
lib_tb <- table(lib_data$kind)
```


```{r}
#| content: valuebox
#| title: "Operators"
list(
  icon = "calculator",
  color = "primary",
  value = lib_tb[["Operator"]]
)
```

```{r}
#| content: valuebox
#| title: "Templates"
list(
  icon = "bar-chart-steps",
  color = "primary",
  value = lib_tb[["Template"]]
)
```

```{r}
#| content: valuebox
#| title: "Datasets"
list(
  icon = "database",
  color = "primary",
  value = lib_tb[["Dataset"]]
)
```

```{r}
#| content: valuebox
#| title: "Apps"
list(
  icon = "box-fill",
  color = "primary",
  value = lib_tb[["App"]]
)
```


## Row {.flow}

```{r}
#| title: "Library Quality"
#| padding: 0px
#| fill: false
knitr::kable(tb)
```

## Row {.flow}

```{r}
#| title: "Issue List"
#| padding: 0px
#| fill: false
knitr::kable(
  df |> 
    select(-retry, -error) |>
    filter(status != "success" & kind != "Unknown")
)
```